# Generated by Django 4.1.5 on 2023-01-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='location',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
