# Generated by Django 4.1.5 on 2023-02-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
