# Generated by Django 4.1.6 on 2023-02-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='is_share',
            field=models.CharField(choices=[('open', '공개'), ('close', '비공개'), ('untitled', '비밀일정')], max_length=20),
        ),
    ]
