# Generated by Django 4.1.6 on 2023-02-13 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wapl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatecomment',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='private_comment_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publiccomment',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='public_comment_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='replyprivatecomment',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='private_reply_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='replypubliccomment',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='public_reply_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='privatecomment',
            name='plan_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_plan', to='wapl.privateplan'),
        ),
        migrations.AlterField(
            model_name='publiccomment',
            name='plan_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_plan', to='wapl.publicplan'),
        ),
        migrations.AlterField(
            model_name='replyprivatecomment',
            name='comment_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_comment', to='wapl.privatecomment'),
        ),
        migrations.AlterField(
            model_name='replypubliccomment',
            name='comment_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_comment', to='wapl.publiccomment'),
        ),
    ]
