# Generated by Django 4.1.6 on 2023-02-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='inputTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_year', models.CharField(max_length=20, null=True)),
                ('input_month', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
