# Generated by Django 4.1.6 on 2023-02-18 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wapl', '0002_alter_meeting_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_attend', models.CharField(choices=[('attend', '참석'), ('absence', '불참'), ('standby', '대기상태')], max_length=10)),
                ('plan', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plan_attend', to='wapl.publicplan')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_attend', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
