# Generated by Django 4.1.6 on 2023-02-02 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wapl', '0002_meeting_owner_alter_meeting_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='user',
            new_name='users',
        ),
    ]
