# Generated by Django 4.1.5 on 2023-02-01 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wapl', '0002_user_default_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='default_image',
        ),
    ]
