# Generated by Django 4.1.6 on 2023-02-03 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wapl', '0002_alter_meeting_owner_alter_plan_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plan',
            new_name='PublicPlan',
        ),
    ]
