# Generated by Django 4.1.5 on 2023-02-01 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wapl', '0002_plan_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_name', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('family', '가족'), ('couple', '연인'), ('club', '동아리'), ('friend', '친구'), ('school', '학교'), ('company', '회사')], max_length=20)),
                ('plan_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_post', to='wapl.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
