# Generated by Django 4.1.6 on 2023-02-05 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wapl', '0003_alter_publicplan_meetings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_share', models.BooleanField()),
                ('meeting', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_shares', to='wapl.meeting')),
                ('plan', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plan_shares', to='wapl.privateplan')),
            ],
        ),
    ]
