# Generated by Django 4.1.5 on 2023-02-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapl', '0003_remove_user_default_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='static/default_profile/1.png', upload_to='profile'),
        ),
    ]
