# Generated by Django 4.1.6 on 2023-02-18 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wapl', '0003_alter_meeting_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='owner',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to=settings.AUTH_USER_MODEL),
        ),
    ]
