# Generated by Django 4.1.6 on 2023-02-03 01:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapl', '0003_rename_user_meeting_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='users',
            field=models.ManyToManyField(related_name='meeting_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
