# Generated by Django 4.1.5 on 2023-02-01 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wapl', '0003_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='plan_post',
        ),
        migrations.AddField(
            model_name='plan',
            name='meeting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_plan', to='wapl.meeting'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_plan', to=settings.AUTH_USER_MODEL),
        ),
    ]
