# Generated by Django 4.1.6 on 2023-02-14 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wapl', '0003_stashimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StashImage',
        ),
    ]
