# Generated by Django 4.1.6 on 2023-02-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapl', '0003_alter_publicplan_meetings'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='default_image',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='image',
            field=models.ImageField(blank=True, upload_to='team_profile'),
        ),
    ]
