# Generated by Django 4.1.6 on 2023-02-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wapl', '0004_share'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='meeting',
            new_name='meetings',
        ),
        migrations.RenameField(
            model_name='share',
            old_name='plan',
            new_name='plans',
        ),
    ]
