# Generated by Django 4.1.6 on 2023-02-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapl', '0004_alter_meeting_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='invitation_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
