# Generated by Django 4.1.6 on 2023-02-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wapl', '0004_meeting_default_image_meeting_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='default_image',
            new_name='default_image_index',
        ),
    ]
