# Generated by Django 4.1.6 on 2023-02-05 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wapl', '0005_rename_meeting_share_meetings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='meetings',
            new_name='meeting',
        ),
        migrations.RenameField(
            model_name='share',
            old_name='plans',
            new_name='plan',
        ),
    ]
