# Generated by Django 4.1.6 on 2023-02-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wapl', '0005_rename_default_image_meeting_default_image_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='default_image_index',
            new_name='default_image',
        ),
    ]
