# Generated by Django 4.1.5 on 2023-02-01 13:04

from django.db import migrations, models
import server.apps.wapl.validators


class Migration(migrations.Migration):

    dependencies = [
        ('wapl', '0005_user_image_alter_comment_plan_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AlterField(
            model_name='plan',
            name='endTime',
            field=models.DateTimeField(validators=[server.apps.wapl.validators.validate_plan_time]),
        ),
        migrations.AlterField(
            model_name='plan',
            name='startTime',
            field=models.DateTimeField(validators=[server.apps.wapl.validators.validate_plan_time]),
        ),
        migrations.AlterField(
            model_name='plan',
            name='title',
            field=models.CharField(max_length=20, validators=[server.apps.wapl.validators.validate_plan_title]),
        ),
    ]
